---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.service.name }}
  labels:
    appname: {{ .Values.service.name }}
  annotations:
    helmChart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      appname: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        appname: {{ .Values.service.name }}
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: appname
      #           operator: In
      #           values:
      #           - {{ .Values.service.name }}
      #       topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Values.service.name }}
        image: gites/{{ .Values.service.name }}:{{ .Values.image.version }}
        imagePullPolicy: Always
        resources:
        {{- toYaml .Values.service.resources | nindent 10 }}
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        readinessProbe:
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /live
            port: 9090
            scheme: HTTP
          periodSeconds: 1
        env:
        {{- range $key, $value := .Values.service.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.service.secret }}
              key: pass
