---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.service.name }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      appname: {{ .Values.service.name }}