{{- if .Values.service.enableServiceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    appname: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      appname: {{ .Values.service.name }}
{{- end }}